name: temporalobe
description: A password management application.

publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9

dev_dependencies:
  blendthink_lints: ^2.0.0
  danger_core: ^1.0.1
  danger_plugin_dart_analyze: ^1.0.1
  flutter_test:
    sdk: flutter
  grinder: ^0.9.2

flutter:
  uses-material-design: true
