name: temporalobe
description: A password management application.

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  animations: ^2.0.3
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.0.3
  gap: ^2.0.0
  go_router: ^4.1.0
  hooks_riverpod: ^2.0.0-dev.9
  isar: ^3.0.0-dev.0
  isar_flutter_libs: ^3.0.0-dev.0
  json_annotation: ^4.6.0
  path_provider: ^2.0.11

dev_dependencies:
  blendthink_lints: ^2.0.0
  build_runner: ^2.1.11
  danger_core: ^1.0.1
  danger_plugin_dart_analyze: ^1.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  go_router_builder: ^1.0.6
  grinder: ^0.9.2
  isar_generator: ^3.0.0-dev.0
  json_serializable: ^6.3.1

dependency_overrides:
  analyzer: ^4.2.0

flutter:
  uses-material-design: true
