name: temporalobe
description: A password management application.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  blendthink_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  grinder: ^0.9.1

flutter:
  uses-material-design: true
