name: temporalobe
description: A password management application.

publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  freezed_annotation: ^2.0.3
  go_router: ^4.1.0
  isar: ^3.0.0-dev.7
  isar_flutter_libs: ^3.0.0-dev.7
  json_annotation: ^4.6.0
  sticky_headers: ^0.3.0+2

dev_dependencies:
  blendthink_lints: ^2.0.0
  build_runner: ^2.1.11
  danger_core: ^1.0.1
  danger_plugin_dart_analyze: ^1.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  go_router_builder: ^1.0.6
  grinder: ^0.9.2
  isar_generator: ^3.0.0-dev.7
  json_serializable: ^6.3.1

dependency_overrides:
  analyzer: ^4.2.0

flutter:
  uses-material-design: true
