name: temporalobe
description: A password management application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  blendthink_lints: ^0.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
