platform :ios do
  lane :update_certificate do
    env = ENV['ENVIRONMENT']
    app_id_suffix = env == 'prd' ? '' : ".#{env}"
    app_id = "dev.blendthink.temporalobe#{app_id_suffix}"

    user = ENV['GITHUB_USER']
    token = ENV["GITHUB_TOKEN"]
    authorization = Base64.strict_encode64("#{user}:#{token}")

    api_key = app_store_connect_api_key(
      key_id: ENV['KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['KEY_CONTENT'],
      )

    match(
      app_identifier: app_id,
      git_basic_authorization: authorization,
      api_key: api_key,
      type: "appstore"
    )
  end
end
