name: Auto Format

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # every Monday at T00:00Z

env:
  FORMAT_PATHS: '.'

jobs:
  auto-format:

    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main

      # https://github.com/kuhnroyal/flutter-fvm-config-action
      - name: fetch flutter config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      # https://github.com/subosito/flutter-action
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}

      - name: format
        run: flutter format $FORMAT_PATHS

      # https://github.com/peter-evans/create-pull-request
      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: auto format
          author: blendthink <info@blendthink.dev>
          title: Auto Format
          body: This was automatically generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          base: main
          branch: auto-format
          branch-suffix: short-commit-hash
