name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: environment
        required: true
        type: environment

jobs:
  deploy:
    runs-on: macos-12
    environment: ${{ github.event.inputs.environment }}

    timeout-minutes: 15

    steps:

      # https://github.com/maxim-lobanov/setup-xcode
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4'

      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3

      # https://github.com/kuhnroyal/flutter-fvm-config-action
      - name: fetch flutter config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      # https://github.com/actions/cache
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.PUB_CACHE }}
            ${{ github.workspace }}/.packages
            ${{ github.workspace }}/.flutter-plugins
            ${{ github.workspace }}/.flutter-plugin-dependencies
            ${{ github.workspace }}/.dart_tool/package_config.json
          key: build-pubspec-${{ hashFiles(format('{0}{1}', github.workspace, '/pubspec.lock')) }}
          restore-keys: |
            build-pubspec-

      # https://github.com/actions/cache
      - name: cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-bundler-

      # https://github.com/actions/cache
      - name: cache pods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      # https://github.com/subosito/flutter-action
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}

      - name: fastlane match
        run: fastlane ios read_certificate
        working-directory: ./ios
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
          GITHUB_USER: ${{ secrets.FASTLANE_MATCH_GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.FASTLANE_MATCH_GITHUB_TOKEN }}

      - name: build ipa
        run: |
          make build-ipa \
            FLAVOR=${{ github.event.inputs.environment }} \
            TEAM_ID=${{ secrets.APP_STORE_CONNECT_TEAM_ID }}

      - name: deploy to testflight
        run: fastlane ios deploy_beta
        working-directory: ./ios
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
